import { library } from '@fortawesome/fontawesome-svg-core';

import { 
  faBaby,
  faChildren,
  faPersonBreastfeeding,
  faUser,
  faWheelchairMove,
  faHouse,
  faPersonPregnant,
  faPerson,
  faFaceSmile,
  faFaceFrown,
  faFaceMeh,
  faAddressBook,
  faAddressCard,
  faComment,
  faCommentDots,
  faCommentAlt,
  faCommentSlash,
  faCommentMedical,
  faCommentSms,
  faKitMedical,
  faHeart,
  faHeartBroken,
  faHeartPulse,
  faCalendar,
  faPenToSquare,
  faTrashCan,
  faGear,
  faMapLocation,
  faMapLocationDot,
  faUserPen,
  faCircleLeft,
  faPlus,
  faCalendarDay,
  faUserDoctor,
  faCalendarPlus,
  faCalendarCheck,
  faClock,
  faTag

} from '@fortawesome/free-solid-svg-icons';

import { 
  faAccessibleIcon,
  faGoogle,
  faLinkedin,
  faLinkedinIn,
  faWhatsapp,
  faWhatsappSquare,

} from '@fortawesome/free-brands-svg-icons';


library.add(
  faHouse,
  faBaby,
  faChildren,
  faCalendarPlus,
  faPersonBreastfeeding,
  faUser,
  faWheelchairMove,
  faPersonPregnant,
  faPerson,
  faFaceSmile,
  faFaceFrown,
  faFaceMeh,
  faAddressBook,
  faAddressCard,
  faComment,
  faCommentDots,
  faCommentAlt,
  faCommentSlash,
  faCommentMedical,
  faCommentSms,
  faKitMedical,
  faHeart,
  faCalendar,
  faHeartBroken,
  faHeartPulse,
  faAccessibleIcon,
  faPenToSquare,
  faTrashCan,
  faGear,
  faMapLocationDot,
  faMapLocation,
  faUserPen,
  faCircleLeft,
  faPlus,
  faCalendarDay,
  faWhatsappSquare,
  faWhatsapp,
  faGoogle,
  faLinkedin,
  faLinkedinIn,
  faUserDoctor,
  faCalendarCheck,
  faClock,
  faTag
);

export const iconClasses = {
  Bébé: 'fa-solid fa-baby',
  Enfants: 'fa-solid fa-children',
  PersonneEtEnfant: 'fa-solid fa-person-breastfeeding',
  Utilisateur: 'fa-solid fa-user',
  FauteuilRoulant: 'fa-solid fa-wheelchair-move',
  Maison: 'fa-solid fa-house',
  PersonneEnceinte: 'fa-solid fa-person-pregnant',
  Personne: 'fa-solid fa-person',
  VisageSouriant: 'fa-solid fa-face-smile',
  VisageTriste: 'fa-solid fa-face-frown',
  VisageNeutre: 'fa-solid fa-face-meh',
  CarnetAdresses: 'fa-solid fa-address-book',
  CarteAdresse: 'fa-solid fa-address-card',
  Commentaire: 'fa-solid fa-comment',
  CommentairePoints: 'fa-solid fa-comment-dots',
  CommentaireAlt: 'fa-solid fa-comment-alt',
  CommentaireBarré: 'fa-solid fa-comment-slash',
  CommentaireMédical: 'fa-solid fa-comment-medical',
  CommentaireSms: 'fa-solid fa-comment-sms',
  TrousseMédicale: 'fa-solid fa-kit-medical',
  Coeur: 'fa-solid fa-heart',
  CoeurBrisé: 'fa-solid fa-heart-broken',
  CoeurBattant: 'fa-solid fa-heart-pulse',
  Calendrier: 'fa-solid fa-calendar',
  IconeAccessible: 'fa-brands fa-accessible-icon',
  Localisation: 'fa-solid fa-map-location-dot',
  LocalisationPoint: 'fa-solid fa-map-location',
  ModifierUtilisateur: 'fa-solid fa-user-pen',
  Modifier: 'fa-solid fa-pen-to-square',
  Whatsapp: 'fa-brands fa-whatsapp-square',
  UtilisateurMedecin: 'fa-solid fa-user-doctor'

};